/*
 * Copyright 2024 Rúben Sousa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.rubensousa.carioca.report.json

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import java.io.File

/**
 * Parses the reports generated by a previous test run.
 * Use [parseTestReports] to retrieve them from a directory
 * or [parseTestReport] to parse an individual report
 */
class JsonReportParser {

    fun parseTestReports(inputDir: File): List<TestReportFile> {
        val reportDir = findReportDir(inputDir) ?: return emptyList()
        val tests = mutableListOf<TestReportFile>()
        reportDir.listFiles()?.forEach { file ->
            if (file.name.endsWith(JsonReportFiles.TEST_REPORT)) {
                parseTestReport(file)?.let {
                    tests.add(TestReportFile(file, it))
                }
            }
        }
        return tests
    }

    fun parseTestReport(file: File): JsonTestReport? {
        return decodeFromFile<JsonTestReport>(file)
    }

    /**
     * Should be future proof, as we find the directory with our own name,
     * without assuming the parent directory structure
     */
    fun findReportDir(inputDir: File): File? {
        if (inputDir.name == JsonReportFiles.REPORT_DIR) {
            return inputDir
        }
        inputDir.listFiles()?.forEach { file ->
            if (file.isDirectory) {
                val reportDir = findReportDir(file)
                if (reportDir != null) {
                    return reportDir
                }
            }
        }
        return null
    }

    @OptIn(ExperimentalSerializationApi::class)
    private inline fun <reified T> decodeFromFile(file: File): T? {
        return try {
            file.inputStream().use {
                Json.decodeFromStream(it)
            }
        } catch (exception: Exception) {
            null
        }
    }

    data class TestReportFile(
        val file: File,
        val report: JsonTestReport,
    )

}
