site_name: Carioca
site_description: 'A collection of testing tools for Android that include flexible reporting capabilities'
site_author: 'Rúben Sousa'
site_url: 'https://rubensousa.github.io/carioca/'
remote_branch: gh-pages
edit_uri: ""
copyright: 'Copyright &copy; 2024 Rúben Sousa'

repo_name: 'Carioca'
repo_url: 'https://github.com/rubensousa/Carioca'

theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: default
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.code.copy

extra:
  report:
    version: '1.0.0-alpha02'
  junit4_rules:
    version: '1.0.0-alpha01'
  allure_plugin:
    version: '1.0.0-alpha03'
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/rubensousa/Carioca'

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: "3"

plugins:
  - markdownextradata: {}

nav:
  - 'Overview': index.md
  - 'Android Test Reports': test-reports-android.md
  - 'Android Allure Plugin': android-allure-plugin.md
  - 'Changelog': changelog.md
  - 'API': api/