name: Push

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.MD'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/docs_pr.yml'
    branches:
      - 'main'

jobs:
  build_libraries:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.0
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: false
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check and build core libraries
        working-directory: ./carioca-report
        run: ./gradlew --build-cache check assemble --stacktrace

      - name: Check and build integration libraries
        run: ./gradlew --build-cache check assemble --stacktrace

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.0
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: false
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Core Snapshots
        working-directory: ./carioca-report
        run: ./gradlew publishMavenPublicationToMavenCentralRepository --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}

      - name: Publish Library Snapshots
        run: ./gradlew publishMavenPublicationToMavenCentralRepository --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}

  create_avds:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, x86]
        target: [ google_apis, android-tv ]
        api-level: [34]
        profile: [pixel_6, tv_1080p]
        exclude:
          - target: google_apis
            profile: tv_1080p
          - target: android-tv
            profile: pixel_6
          - arch: x86
            profile: pixel_6
          - arch: x86_64
            profile: tv_1080p

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.0
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: false
          cache: "gradle"

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          android: false

      # Retrieve the cached emulator snapshot.
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.profile }}

      - name: Create AVD snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: ${{ matrix.profile }}
          disable-animations: false
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot."

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.api-level }}-${{ matrix.arch }}-instrumentation-test-results
          path: |
            logs/**
        if: always()
